"""Initial schema with persona_editor prefix

Revision ID: f7c20f51b58f
Revises: 
Create Date: 2025-11-06 08:30:48.836250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f7c20f51b58f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

llm_default_category_enum = postgresql.ENUM(
    'TOOLS',
    'PERMISSIONS',
    'GOALS',
    'PROMPTS',
    'TONES',
    'ROLES',
    name='persona_editor_llm_default_category',
    create_type=False,
)

TABLE_INDEXES = {
    'persona_editor_audit_logs': [
        'ix_persona_editor_audit_logs_timestamp',
        'ix_persona_editor_audit_logs_persona_id',
        'ix_persona_editor_audit_logs_id',
        'ix_persona_editor_audit_logs_action',
        'idx_audit_persona_timestamp',
        'idx_audit_action_timestamp',
    ],
    'persona_editor_personas': [
        'ix_persona_editor_personas_name',
        'ix_persona_editor_personas_id',
    ],
    'persona_editor_llm_defaults': [
        'ix_persona_editor_llm_defaults_is_default',
        'ix_persona_editor_llm_defaults_id',
        'ix_persona_editor_llm_defaults_category',
        'idx_llm_defaults_category_is_default',
    ],
}


def upgrade() -> None:
    """Upgrade schema."""
    # Create enum type if it doesn't exist
    llm_default_category_enum.create(op.get_bind(), checkfirst=True)

    # Drop existing tables if they exist (they're empty anyway)
    # Drop in reverse order due to foreign key constraints
    op.execute("DROP TABLE IF EXISTS persona_editor_audit_logs CASCADE")
    op.execute("DROP TABLE IF EXISTS persona_editor_personas CASCADE")
    op.execute("DROP TABLE IF EXISTS persona_editor_llm_defaults CASCADE")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persona_editor_llm_defaults',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('category', llm_default_category_enum, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_llm_defaults_category_is_default', 'persona_editor_llm_defaults', ['category', 'is_default'], unique=False)
    op.create_index(op.f('ix_persona_editor_llm_defaults_category'), 'persona_editor_llm_defaults', ['category'], unique=False)
    op.create_index(op.f('ix_persona_editor_llm_defaults_id'), 'persona_editor_llm_defaults', ['id'], unique=False)
    op.create_index(op.f('ix_persona_editor_llm_defaults_is_default'), 'persona_editor_llm_defaults', ['is_default'], unique=False)
    op.create_table('persona_editor_personas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('tone', sa.String(), nullable=False),
    sa.Column('llm_provider', sa.String(), nullable=False),
    sa.Column('llm_temperature', sa.Float(), nullable=False),
    sa.Column('llm_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('goals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tools', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('permitted_to', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prompt_system_template', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prompt_user_template', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prompt_context_template', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prompt_instruction', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('agent_delegate', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('agent_call', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('context_files', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('memory', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persona_editor_personas_id'), 'persona_editor_personas', ['id'], unique=False)
    op.create_index(op.f('ix_persona_editor_personas_name'), 'persona_editor_personas', ['name'], unique=False)
    op.create_table('persona_editor_audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('persona_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('changes', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['persona_id'], ['persona_editor_personas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_action_timestamp', 'persona_editor_audit_logs', ['action', 'timestamp'], unique=False)
    op.create_index('idx_audit_persona_timestamp', 'persona_editor_audit_logs', ['persona_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_persona_editor_audit_logs_action'), 'persona_editor_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_persona_editor_audit_logs_id'), 'persona_editor_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_persona_editor_audit_logs_persona_id'), 'persona_editor_audit_logs', ['persona_id'], unique=False)
    op.create_index(op.f('ix_persona_editor_audit_logs_timestamp'), 'persona_editor_audit_logs', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema - safely tear down only the tables created here."""
    # Drop dependent tables first to respect FK relationships
    teardown_order = (
        'persona_editor_audit_logs',
        'persona_editor_personas',
        'persona_editor_llm_defaults',
    )

    for table_name in teardown_order:
        for index_name in TABLE_INDEXES.get(table_name, []):
            op.drop_index(index_name, table_name=table_name)
        op.drop_table(table_name)

    # Drop enum type last since it is used by persona_editor_llm_defaults
    llm_default_category_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
