"""
Generated types from common schemas.
Auto-generated by ./common/scripts/generate-types.sh
"""

# TODO: Add generated Pydantic models from JSON schemas
# TODO: Add generated protobuf classes

__all__ = []
