#!/bin/bash
# Generate types from schemas in ./common/schemas/

set -e

COMMON_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCHEMAS_DIR="$COMMON_DIR/schemas"
TYPES_DIR="$COMMON_DIR/types"

echo "Generating types from schemas..."
echo "Schemas: $SCHEMAS_DIR"
echo "Output: $TYPES_DIR"

# Create output directories
mkdir -p "$TYPES_DIR/python"
mkdir -p "$TYPES_DIR/typescript"

# Initialize Python types module
cat > "$TYPES_DIR/python/__init__.py" << 'EOF'
"""
Generated types from common schemas.
Auto-generated by ./common/scripts/generate-types.sh
"""

# TODO: Add generated Pydantic models from JSON schemas
# TODO: Add generated protobuf classes

__all__ = []
EOF

# Initialize TypeScript types module
cat > "$TYPES_DIR/typescript/index.ts" << 'EOF'
/**
 * Generated types from common schemas
 * Auto-generated by ./common/scripts/generate-types.sh
 */

// TODO: Add generated Zod schemas from JSON schemas
// TODO: Add generated protobuf classes

export {};
EOF

echo "✓ Type generation complete"
echo "  - Python types: $TYPES_DIR/python/"
echo "  - TypeScript types: $TYPES_DIR/typescript/"
echo ""
echo "Note: Add datamodel-code-generator (Python) and json-schema-to-zod (TS) for full code generation"
