/**
 * Generated types from common schemas
 * Auto-generated by ./common/scripts/generate-types.sh
 */

// TODO: Add generated Zod schemas from JSON schemas
// TODO: Add generated protobuf classes

export {};
